### PR TITLE
Add Student model to `large_models` array

### PR DESCRIPTION
**Pull request by shreyansh23**
Admin add/edit view of models of having foreign key to `Student` fails to open student count when goes near 7-8k. Adding `Student` to `large_models` array to have similar fix as that of `User` and `Person` model.

### CODE REVIEW

**Comment by dhruvkb** [comment]
Makes sense. Are there any other models with such large numbers?

**Comment by shreyansh23** [comment]
> Makes sense. Are there any other models with such large numbers?

Presently, `FacultyMember` count goes to 1k. No problem with that as of now but it would be better to have similar fix for that model as well.
Apart from that, `Candidate` model face similar problem. The same problem existed in old channeli as well. But for `Candidate` model, it would be better to handle this on app level `admin.py` using `raw_id_field` for `candidate` field.

**Comment by dhruvkb** [comment]
Add `FacultyMember` to the list and update the PR.

**Comment by ayushjn20** [comment]
Nice work!

**Pull request merged**
