### PR TITLE
Add a confidence argument in the AspectRatio validator to allow a range of aspect ratio

### PR DESCRIPTION
**Pull request by pradumangoyal**

### CODE REVIEW

**Comment by pradumangoyal** [comment]
@dhruvkb @ayushjn20 Please have a look on this.

**Comment by dhruvkb** [comment]
I'm confused, why do we want flexibility in image aspect ratios? Doesn't that defeat the point of having aspect ratio validation?

**Comment by pradumangoyal** [comment]
The cropper on the frontend missed some pixels while selecting, so I've put a small interval there. In the application model, I think we can't restrict the logo to be perfectly square.

**Comment by dhruvkb** [comment]
Then the cropper UI needs to be fixed. Compensation for some component's faults should not be made on a different component.

**Comment by ayushjn20** [comment]
~~_confidence_~~ -> _tolerance_ 
Tolerance is OK if it is _very_ small, let's say you are uploading a logo of 32 * 32, but the cropper can crop out 31 * 32, etc. Having a 5% tolerance is useful, otherwise the backend with strict AspectRatio validator will sometimes allow, sometimes won't allow such small differences.

**Comment by dhruvkb** [comment]
Yeah @pradumangoyal, I agree with @ayushjn20 and I'm cool with upto 5% tolerance, any more than that means your cropper is practically broken.

**Comment by algomaster99** [comment]
@pradumangoyal a perfectly square image wasn't captured because it was the `react-cropper`'s fault?

**Pull request merged**
